cafeadmin/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path("", RedirectView.as_view(url='planner')),
    path("/", RedirectView.as_view(url='planner')),
    path("admin/", admin.site.urls),
    path("planner/", include("shift_planner.urls")),
    path("accounts/", include('django.contrib.auth.urls')),
]

shift_planner/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.contrib import admin
from . import views

app_name = "planner"
urlpatterns = [
    # path('', views.overview, name = 'index'),
    path('', views.overview, name = 'overview'),
    path('shift/<int:shift_id>', views.shift_detail),
    path('shift/<int:shift_id>/register', views.shift_register_myself),
    path('shift/<int:shift_id>/register/<int:employee_id>', views.shift_register_other),
    path('shift/<int:shift_id>/unregister', views.shift_unregister_myself),
    path('shift/<int:shift_id>/unregister/<int:employee_id>', views.shift_unregister_other),
    path('monthly', views.shift_by_month, name='monthly'),
    path('monthly/', views.shift_by_month),
    path('monthly/<int:year>/<int:month>', views.shift_by_month),
]

shift_planner/models.py
from typing_extensions import Self

from django.db import models
from django.db.models import Count
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _
from datetime import date, timedelta, datetime
from calendar import monthrange, month


from .constants import UNREGISTER_MIN_BEFORE_DAYS

class CustomUser(AbstractUser):
    pass
    # add additional fields in here

    def __str__(self):
        return self.username
    
    class Meta:
        verbose_name = "User"
        verbose_name_plural = "User"

class Shift(models.Model):
    shift_date = models.DateField(verbose_name = _("Date"))
    starts_at = models.TimeField(verbose_name = _("Starts at"))
    ends_at = models.TimeField(verbose_name = _("Ends at"))
    title = models.CharField(max_length = 80, default = '', verbose_name = _("Title"), blank=False)
    required_employees_min = models.IntegerField(default = 0, verbose_name = _("Minimum required employees"))
    required_employees_max = models.IntegerField(default = 0, verbose_name = _("Maximum required employees"))

    class Meta:
        verbose_name = "Schicht"
        verbose_name_plural = "Schichten"
        permissions = (("can_register_others", "Register other users"),
                       ("does_planning", "Sees planning relevant details"),)

    def __str__(self):
        dFormat = '%d.%m.%y'
        tFormat = '%H:%M'
        return f"{self.shift_date.strftime(dFormat)}, {self.starts_at.strftime(tFormat)}-{self.ends_at.strftime(tFormat)}: {self.title}"

    @property
    def unregister_possible(self):
        last_unregister_date = self.shift_date - timedelta(days = UNREGISTER_MIN_BEFORE_DAYS)
        today = datetime.now().date()
        is_possible = True if today < last_unregister_date else False
        return is_possible

    @property
    def is_past(self):
        start_date = datetime.combine(self.shift_date, self.starts_at)
        return ( start_date < datetime.now() )

    @property
    def registered_employees(self):
        registrations = ShiftRegistration.objects.filter(shift = self)
        return registrations.count()

    def is_registered(self, user: CustomUser):
        registration = ShiftRegistration.objects.filter(shift = self, registree = user)
        return True if registration.count() > 0 else False

    def register(self, user: CustomUser):
        if self.is_registered(user) == False:
            registration = ShiftRegistration(shift = self, registree = user)
            registration.save()

    def unregister(self, user: CustomUser):
        registrations = ShiftRegistration.objects.filter(shift=self, registree=user)
        registrations.delete()

    @staticmethod
    def get_shifts_by_user(user: CustomUser):
        return Shift.objects.filter(registree=user)
    
    # TODO remove
    # @staticmethod
    # def get_shifts_for_range(date_from: date, date_to: date):
    #     shifts = Shift.objects.filter(shift_date__gte = date_from, shift_date__lte = date_to)
    #     holidays = Holiday.objects.filter(shift_date__gte = date_from, shift_date__lte = date_to)
    #     days = []
    #     delta = timedelta( days = 1 )

    #     while( date_from <= date_to ):
    #         holiday = holidays.filter(shift_date=date_from)
    #         shifts_for_date = shifts.filter(shift_date = date_from).order_by('starts_at')

    #         days.append( CalendarDay( date_from, holiday, shifts_for_date ) )
    #         date_from += delta
    #     return days

class ShiftRegistration(models.Model):
    shift = models.ForeignKey(Shift, on_delete=models.DO_NOTHING)
    registree = models.ForeignKey(CustomUser, related_name='user_registree', on_delete=models.CASCADE, default='')
    registered_at = models.DateTimeField(null = True, blank = True)
    registered_by = models.ForeignKey(CustomUser, related_name='user_registered_by', on_delete=models.DO_NOTHING, null = True, blank = True)

    class Meta:
        verbose_name = "Schichtanmeldung"
        verbose_name_plural = "Schichtanmeldungen"

class Holiday(models.Model):
    date = models.DateField(primary_key=True)
    name = models.CharField(max_length = 40, default = '')

    class Meta:
        verbose_name = "Feiertag"
        verbose_name_plural = "Feiertage"

    def __str__(self):
        dFormat = '%d.%m.%y'
        return f"{self.date.strftime(dFormat)} - {self.name}"


class CalendarDay:
    def __init__(self, day : date, holiday : Holiday, shifts):
        self.date = day
        self.holiday = holiday
        self.shifts = shifts
        now = datetime.today().date()
        self.is_past = False if day > now else True

    @staticmethod
    def getSpecificDay(specific_date : date, user : CustomUser) -> Self:
        shifts = Shift.objects.filter(shift_date = specific_date).order_by('starts_at')
        for shift in shifts:
            shift.is_registered = shift.is_registered(user)

        holidays = Holiday.objects.filter(date = specific_date)
        return CalendarDay( day=specific_date, holiday=holidays.first(), shifts=shifts )

class CalendarWeek:
    # def __init__(self, monday : date, days : list[CalendarDay]):
    def __init__(self, monday : date, days):
        self.monday = monday
        self.sunday = monday + timedelta(days = 6)
        self.weeknum = monday.isocalendar()[1]
        self.days = days
    
    @staticmethod
    def getSpecificWeek(any_day_of_week : date, user : CustomUser) -> Self:
        weekday = datetime(any_day_of_week.year, any_day_of_week.month, any_day_of_week.day).weekday()
        monday = any_day_of_week - timedelta(days = weekday)
        sunday = monday + timedelta(days = 6)
        days = []
        day = monday
        
        while( day <= sunday ):
            days.append( CalendarDay.getSpecificDay(day, user) )
            day += timedelta(days=1)

        return CalendarWeek(monday=monday, days=days)
    
class CalendarMonth:
    # def __init__(self, month : int, year : int, weeks : list[CalendarWeek]):
    def __init__(self, month : int, year : int, weeks):
        self.month = month
        self.year = year
        self.weeks = weeks

    @staticmethod
    def getMonth(month : int, year : int, user : CustomUser):
        # TODO remove user parameter
        weeks = []

        firstday = date(year, month, day = 1)
        last_day = date(year, month, day = 1) + timedelta(days = monthrange(year, month)[1] - 1)
        day = firstday

        while day <= last_day:
            weeks.append(CalendarWeek.getSpecificWeek(day, user))
            day += timedelta(days=7)

        return CalendarMonth(month, year, weeks)

shift_planner/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = CustomUser
        fields = ("username", "email")

class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ("username", "email")

shift_planner/views.py
from django.db.models import Q, F
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required, permission_required

from datetime import datetime, timedelta, date

from .models import Shift, ShiftRegistration, CalendarWeek, CalendarMonth, CustomUser
from .constants import APP_DISPLAY_NAME

# TODO remove
@login_required(login_url='/accounts/login/')
def list_shifts(request):
    shifts = Shift.objects.order_by("shift_date")
    return render(request, "shifts/list.html", _get_shift_list_context(request, shifts))


# TODO improve
@login_required(login_url='/accounts/login/')
@permission_required('shift_planner.does_planning')
def shift_detail(request, shift_id):
    shift = get_object_or_404(Shift, pk=shift_id)
    registrations = ShiftRegistration.objects.filter(shift=shift_id)
    
    registered_usernames = [ x.registree for x in registrations ]
    all_users = CustomUser.objects.all().order_by('last_name')
    not_registered_users = [x for x in all_users if x not in registered_usernames]

    return render(request, "shifts/detail.html", {"shift": shift, "registrations": registrations, "not_registered_users": not_registered_users, "nav_menu_item": "detail"})


@login_required(login_url='/accounts/login/')
def shift_register_myself(request, shift_id):
    if request.user.is_authenticated:
        shift = Shift.objects.get(pk=shift_id)
        shift.register(request.user)
    return HttpResponseRedirect(request.META['HTTP_REFERER'])
#TODO provide a notification


@login_required(login_url='/accounts/login/')
def shift_unregister_myself(request, shift_id):
    if request.user.is_authenticated:
        shift = Shift.objects.get(pk=shift_id)
        shift.unregister(request.user)
    return HttpResponseRedirect(request.META['HTTP_REFERER'])


@permission_required('shift_planner.can_register_others')
@login_required(login_url='/accounts/login/')
def shift_unregister_other(request, shift_id, employee_id):
    shift = Shift.objects.get(pk=shift_id)
    employee = CustomUser.objects.get(id=employee_id)
    shift.unregister(employee)
    return HttpResponseRedirect(request.META['HTTP_REFERER'])


@permission_required('shift_planner.can_register_others')
@login_required(login_url='/accounts/login/')
def shift_register_other(request, shift_id, employee_id):
    shift = Shift.objects.get(pk=shift_id)
    employee = CustomUser.objects.get(id=employee_id)
    shift.register(employee)
    return HttpResponseRedirect(request.META['HTTP_REFERER'])


@login_required(login_url='/accounts/login/')
def shift_by_month(request, year = 0, month = 0):
    # TODO check for user authenticated
    year = datetime.now().year if year == 0 else year
    month = datetime.now().month if month == 0 else month
    firstday = date(year, month, 1)

    calendarMonth = CalendarMonth.getMonth( month, year, request.user )

    calendarMonth.month = month
    calendarMonth.year = year

    context = { "first_day": firstday,
                "previous": { 
                    "year": (firstday - timedelta(days=1)).year, 
                    "month": (firstday - timedelta(days=1)).month 
                },
                "next": {
                    "year": (firstday + timedelta(days=1)).year, 
                    "month": (firstday + timedelta(days=31)).month
                },
                "month": calendarMonth,
                "nav_menu_item": "by_month" }

    return render(request, "shifts/monthly.html", context)


@staticmethod
def _add_constants(context):
    context += { "application_display_name": APP_DISPLAY_NAME }

# TODO remove
# def shift_my(request):
#     shifts = []
#     if request.user.is_authenticated:
#         shifts = Shift.objects.filter(registree = request.user).order_by("date")
#     return render(request, "shifts/list.html", _get_shift_list_context(request, shifts))


def _get_shift_list_context(request, shifts):
    username = 'None'
    if request.user.is_authenticated:
        username = request.user.username
        for shift in shifts:
            shift.is_registered = shift.is_registered(request.user)
    context = {"shifts": shifts, "user": username, "is_authenticated": request.user.is_authenticated}
    return context

@login_required(login_url='/accounts/login/')
def overview(request):
    # TODO check that user is registered, otherwise to other endpoint

    my_next_shifts = Shift.objects.filter(
        Q(shiftregistration__registree = request.user.id),
        Q(shift_date__gte = datetime.today())
    ).order_by("shift_date", "starts_at")[:3]

    for shift in my_next_shifts:
        shift.is_registered = shift.is_registered(request.user)

    next_weeks = []
    next_weeks.append(CalendarWeek.getSpecificWeek(datetime.today().date(), request.user))
    next_weeks.append(CalendarWeek.getSpecificWeek(datetime.today().date() + timedelta(days=7), request.user))

    context = {"my_next_shifts": my_next_shifts, "next_weeks": next_weeks, "nav_menu_item": "overview"}
    return render(request, "shifts/overview.html", context)

# def logout(request):
#     logout(request)
#     # TODO redirect

# def login(request):
#     username = request.POST["id_username"]
#     password = request.POST["id_password"]
#     user = authenticate(request, username=username, password=password)
#     if user is not None:
#         login(request, user)
#         # Redirect to a success page.
#         ...
#     else:
#         # Return an 'invalid login' error message.
#         ...

shift_planner/templates/_logout.html
{% load i18n %}

<form class="text-center" action="{% url 'logout' %}" method="post">
    {% csrf_token %}
    <button class="btn btn-primary" type="submit">{% translate "Log Out" %}</button>
</form>

shift_planner/templates/base.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html>
    <head lang="en">
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- <link rel="stylesheet" href="{% static 'shiftplanner.css' %}"> -->

        <!-- Bootstrap -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">        
        <link rel="stylesheet" href="{% static 'starter-template.css' %}">
        <title>{% block title %}Shift Planner{% endblock %}</title>
    </head>

    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
          <div class="container-fluid">
            <a class="navbar-brand" href="#">Organization</a>
            {% if user.is_authenticated %}
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav me-auto">
                <li class="nav-item">
                  <a class="nav-link {% if nav_menu_item and nav_menu_item == 'overview' %} active {% endif %}" href="{% url 'planner:overview' %}">{% translate "My Shiftplan" %}</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link {% if nav_menu_item and nav_menu_item == 'by_month' %} active {% endif %}" href="{% url 'planner:monthly' %}">{% translate "Overview by month" %}</a>
                </li>
                {% if user.is_staff %}
                  <li class="nav-item">
                    <a class="nav-link" href="/admin" target="_blank">{% translate "Administration" %}</a>
                  </li>
                {% endif %}
              </ul>
              <ul class="navbar-nav me-2">
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    {% blocktranslate with name=user.get_full_name %} Logged in as: {{ name }} {% endblocktranslate %}
                  </a>
                  <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="{% url 'password_change' %}">{% translate "Change password" %}</a></li>
                    <li><hr class="dropdown-divider"></li>
                    <li class="nav-item">
                      {% include '_logout.html' %}
                    </li>
                  </ul>
              </ul>
            </div>
            {% endif %}
          </div>
        </nav>
        
        <main role="main" class="container">
          <div class="starter-template">
              {% block content %}{% endblock content %}
            </div>
          </main>
          



          <!--JavaScript-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
        <!-- <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script> -->
    </body>
</html>