cafeadmin/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path("", RedirectView.as_view(url='planner')),
    path("/", RedirectView.as_view(url='planner')),
    path("admin/", admin.site.urls),
    path("planner/", include("shift_planner.urls")),
    path("accounts/", include('django.contrib.auth.urls')),
]

shift_planner/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.contrib import admin
from . import views

app_name = "planner"
urlpatterns = [
    # path('', views.overview, name = 'index'),
    path('', views.overview, name = 'overview'),
    path('shift/<int:shift_id>', views.shift_detail),
    path('shift/<int:shift_id>/register', views.shift_register_myself),
    path('shift/<int:shift_id>/register/<int:employee_id>', views.shift_register_other),
    path('shift/<int:shift_id>/unregister', views.shift_unregister_myself),
    path('shift/<int:shift_id>/unregister/<int:employee_id>', views.shift_unregister_other),
    path('monthly', views.shift_by_month, name='monthly'),
    path('monthly/', views.shift_by_month),
    path('monthly/<int:year>/<int:month>', views.shift_by_month),
]

shift_planner/models.py
from typing_extensions import Self

from django.db import models
from django.db.models import Count
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _
from datetime import date, timedelta, datetime
from calendar import monthrange, month


from .constants import UNREGISTER_MIN_BEFORE_DAYS

class CustomUser(AbstractUser):
    pass
    # add additional fields in here

    def __str__(self):
        return self.username
    
    class Meta:
        verbose_name = "User"
        verbose_name_plural = "User"

class Shift(models.Model):
    shift_date = models.DateField(verbose_name = _("Date"))
    starts_at = models.TimeField(verbose_name = _("Starts at"))
    ends_at = models.TimeField(verbose_name = _("Ends at"))
    title = models.CharField(max_length = 80, default = '', verbose_name = _("Title"), blank=False)
    required_employees_min = models.IntegerField(default = 0, verbose_name = _("Minimum required employees"))
    required_employees_max = models.IntegerField(default = 0, verbose_name = _("Maximum required employees"))

    class Meta:
        verbose_name = "Schicht"
        verbose_name_plural = "Schichten"
        permissions = (("can_register_others", "Register other users"),
                       ("does_planning", "Sees planning relevant details"),)

    def __str__(self):
        dFormat = '%d.%m.%y'
        tFormat = '%H:%M'
        return f"{self.shift_date.strftime(dFormat)}, {self.starts_at.strftime(tFormat)}-{self.ends_at.strftime(tFormat)}: {self.title}"

    @property
    def unregister_possible(self):
        last_unregister_date = self.shift_date - timedelta(days = UNREGISTER_MIN_BEFORE_DAYS)
        today = datetime.now().date()
        is_possible = True if today < last_unregister_date else False
        return is_possible

    @property
    def is_past(self):
        start_date = datetime.combine(self.shift_date, self.starts_at)
        return ( start_date < datetime.now() )

    @property
    def registered_employees(self):
        registrations = ShiftRegistration.objects.filter(shift = self)
        return registrations.count()

    def is_registered(self, user: CustomUser):
        registration = ShiftRegistration.objects.filter(shift = self, registree = user)
        return True if registration.count() > 0 else False

    def register(self, user: CustomUser):
        if self.is_registered(user) == False:
            registration = ShiftRegistration(shift = self, registree = user)
            registration.save()

    def unregister(self, user: CustomUser):
        registrations = ShiftRegistration.objects.filter(shift=self, registree=user)
        registrations.delete()

    @staticmethod
    def get_shifts_by_user(user: CustomUser):
        return Shift.objects.filter(registree=user)
    
    # TODO remove
    # @staticmethod
    # def get_shifts_for_range(date_from: date, date_to: date):
    #     shifts = Shift.objects.filter(shift_date__gte = date_from, shift_date__lte = date_to)
    #     holidays = Holiday.objects.filter(shift_date__gte = date_from, shift_date__lte = date_to)
    #     days = []
    #     delta = timedelta( days = 1 )

    #     while( date_from <= date_to ):
    #         holiday = holidays.filter(shift_date=date_from)
    #         shifts_for_date = shifts.filter(shift_date = date_from).order_by('starts_at')

    #         days.append( CalendarDay( date_from, holiday, shifts_for_date ) )
    #         date_from += delta
    #     return days

class ShiftRegistration(models.Model):
    shift = models.ForeignKey(Shift, on_delete=models.DO_NOTHING)
    registree = models.ForeignKey(CustomUser, related_name='user_registree', on_delete=models.CASCADE, default='')
    registered_at = models.DateTimeField(null = True, blank = True)
    registered_by = models.ForeignKey(CustomUser, related_name='user_registered_by', on_delete=models.DO_NOTHING, null = True, blank = True)

    class Meta:
        verbose_name = "Schichtanmeldung"
        verbose_name_plural = "Schichtanmeldungen"

class Holiday(models.Model):
    date = models.DateField(primary_key=True)
    name = models.CharField(max_length = 40, default = '')

    class Meta:
        verbose_name = "Feiertag"
        verbose_name_plural = "Feiertage"

    def __str__(self):
        dFormat = '%d.%m.%y'
        return f"{self.date.strftime(dFormat)} - {self.name}"


class CalendarDay:
    def __init__(self, day : date, holiday : Holiday, shifts):
        self.date = day
        self.holiday = holiday
        self.shifts = shifts
        now = datetime.today().date()
        self.is_past = False if day > now else True

    @staticmethod
    def getSpecificDay(specific_date : date, user : CustomUser) -> Self:
        shifts = Shift.objects.filter(shift_date = specific_date).order_by('starts_at')
        for shift in shifts:
            shift.is_registered = shift.is_registered(user)

        holidays = Holiday.objects.filter(date = specific_date)
        return CalendarDay( day=specific_date, holiday=holidays.first(), shifts=shifts )

class CalendarWeek:
    # def __init__(self, monday : date, days : list[CalendarDay]):
    def __init__(self, monday : date, days):
        self.monday = monday
        self.sunday = monday + timedelta(days = 6)
        self.weeknum = monday.isocalendar()[1]
        self.days = days
    
    @staticmethod
    def getSpecificWeek(any_day_of_week : date, user : CustomUser) -> Self:
        weekday = datetime(any_day_of_week.year, any_day_of_week.month, any_day_of_week.day).weekday()
        monday = any_day_of_week - timedelta(days = weekday)
        sunday = monday + timedelta(days = 6)
        days = []
        day = monday
        
        while( day <= sunday ):
            days.append( CalendarDay.getSpecificDay(day, user) )
            day += timedelta(days=1)

        return CalendarWeek(monday=monday, days=days)
    
class CalendarMonth:
    # def __init__(self, month : int, year : int, weeks : list[CalendarWeek]):
    def __init__(self, month : int, year : int, weeks):
        self.month = month
        self.year = year
        self.weeks = weeks

    @staticmethod
    def getMonth(month : int, year : int, user : CustomUser):
        # TODO remove user parameter
        weeks = []

        firstday = date(year, month, day = 1)
        last_day = date(year, month, day = 1) + timedelta(days = monthrange(year, month)[1] - 1)
        day = firstday

        while day <= last_day:
            weeks.append(CalendarWeek.getSpecificWeek(day, user))
            day += timedelta(days=7)

        return CalendarMonth(month, year, weeks)

shift_planner/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = CustomUser
        fields = ("username", "email")

class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ("username", "email")

shift_planner/views.py
from django.db.models import Q, F
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required, permission_required

from datetime import datetime, timedelta, date

from .models import Shift, ShiftRegistration, CalendarWeek, CalendarMonth, CustomUser
from .constants import APP_DISPLAY_NAME

# TODO remove
@login_required(login_url='/accounts/login/')
def list_shifts(request):
    shifts = Shift.objects.order_by("shift_date")
    return render(request, "shifts/list.html", _get_shift_list_context(request, shifts))


# TODO improve
@login_required(login_url='/accounts/login/')
@permission_required('shift_planner.does_planning')
def shift_detail(request, shift_id):
    shift = get_object_or_404(Shift, pk=shift_id)
    registrations = ShiftRegistration.objects.filter(shift=shift_id)
    
    registered_usernames = [ x.registree for x in registrations ]
    all_users = CustomUser.objects.all().order_by('last_name')
    not_registered_users = [x for x in all_users if x not in registered_usernames]

    return render(request, "shifts/detail.html", {"shift": shift, "registrations": registrations, "not_registered_users": not_registered_users, "nav_menu_item": "detail"})


@login_required(login_url='/accounts/login/')
def shift_register_myself(request, shift_id):
    if request.user.is_authenticated:
        shift = Shift.objects.get(pk=shift_id)
        shift.register(request.user)
    return HttpResponseRedirect(request.META['HTTP_REFERER'])
#TODO provide a notification


@login_required(login_url='/accounts/login/')
def shift_unregister_myself(request, shift_id):
    if request.user.is_authenticated:
        shift = Shift.objects.get(pk=shift_id)
        shift.unregister(request.user)
    return HttpResponseRedirect(request.META['HTTP_REFERER'])


@permission_required('shift_planner.can_register_others')
@login_required(login_url='/accounts/login/')
def shift_unregister_other(request, shift_id, employee_id):
    shift = Shift.objects.get(pk=shift_id)
    employee = CustomUser.objects.get(id=employee_id)
    shift.unregister(employee)
    return HttpResponseRedirect(request.META['HTTP_REFERER'])


@permission_required('shift_planner.can_register_others')
@login_required(login_url='/accounts/login/')
def shift_register_other(request, shift_id, employee_id):
    shift = Shift.objects.get(pk=shift_id)
    employee = CustomUser.objects.get(id=employee_id)
    shift.register(employee)
    return HttpResponseRedirect(request.META['HTTP_REFERER'])


@login_required(login_url='/accounts/login/')
def shift_by_month(request, year = 0, month = 0):
    # TODO check for user authenticated
    year = datetime.now().year if year == 0 else year
    month = datetime.now().month if month == 0 else month
    firstday = date(year, month, 1)

    calendarMonth = CalendarMonth.getMonth( month, year, request.user )

    calendarMonth.month = month
    calendarMonth.year = year

    context = { "first_day": firstday,
                "previous": { 
                    "year": (firstday - timedelta(days=1)).year, 
                    "month": (firstday - timedelta(days=1)).month 
                },
                "next": {
                    "year": (firstday + timedelta(days=1)).year, 
                    "month": (firstday + timedelta(days=31)).month
                },
                "month": calendarMonth,
                "nav_menu_item": "by_month" }

    return render(request, "shifts/monthly.html", context)


@staticmethod
def _add_constants(context):
    context += { "application_display_name": APP_DISPLAY_NAME }

# TODO remove
# def shift_my(request):
#     shifts = []
#     if request.user.is_authenticated:
#         shifts = Shift.objects.filter(registree = request.user).order_by("date")
#     return render(request, "shifts/list.html", _get_shift_list_context(request, shifts))


def _get_shift_list_context(request, shifts):
    username = 'None'
    if request.user.is_authenticated:
        username = request.user.username
        for shift in shifts:
            shift.is_registered = shift.is_registered(request.user)
    context = {"shifts": shifts, "user": username, "is_authenticated": request.user.is_authenticated}
    return context

@login_required(login_url='/accounts/login/')
def overview(request):
    # TODO check that user is registered, otherwise to other endpoint

    my_next_shifts = Shift.objects.filter(
        Q(shiftregistration__registree = request.user.id),
        Q(shift_date__gte = datetime.today())
    ).order_by("shift_date", "starts_at")[:3]

    for shift in my_next_shifts:
        shift.is_registered = shift.is_registered(request.user)

    next_weeks = []
    next_weeks.append(CalendarWeek.getSpecificWeek(datetime.today().date(), request.user))
    next_weeks.append(CalendarWeek.getSpecificWeek(datetime.today().date() + timedelta(days=7), request.user))

    context = {"my_next_shifts": my_next_shifts, "next_weeks": next_weeks, "nav_menu_item": "overview"}
    return render(request, "shifts/overview.html", context)

# def logout(request):
#     logout(request)
#     # TODO redirect

# def login(request):
#     username = request.POST["id_username"]
#     password = request.POST["id_password"]
#     user = authenticate(request, username=username, password=password)
#     if user is not None:
#         login(request, user)
#         # Redirect to a success page.
#         ...
#     else:
#         # Return an 'invalid login' error message.
#         ...

shift_planner/templates/shifts/detail.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% translate "Shift Planner" %}: {% translate "Detail View" %}{% endblock %}
{% block content %}

<h2 class="mb-3">{% translate "Detail View" %}</h2>

<div class="container text-start">
    <div class="row align-items-start mb-3">
        <div class="col">
            <h4>{% translate "Details" %}</h4>
            <table class="table text-start">
                <tr><td>{% translate "Date"%}:</td><td>{{ shift.shift_date }}</td></tr>
                <tr><td>{% translate "Starts at"%}:</td><td>{{ shift.starts_at }}</td></tr>
                <tr><td>{% translate "Ends at"%}:</td><td>{{ shift.ends_at }}</td></tr>
                <tr><td>{% translate "Description"%}:</td><td>{{ shift.title }}</td></tr>
                <tr><td>{% translate "Required employees"%}:</td><td>{{ shift.required_employees_min }}</td></tr>
                <tr>
                    <td>{% translate "Registered employees"%}:</td>
                    <td>
                        <p>{{ shift.registered_employees }}</p>
                        {% if shift.required_employees_min > shift.registered_employees %}
                            <div class="alert alert-danger" role="alert">
                                {% translate "Understaffed." %}
                            </div>
                        {% endif %}
                    </td>
                </tr>
            </table>
        </div>
        <div class="col">
            <h4>{% translate "Registered for this shift" %}</h4>
            {% if registrations %}{% else %}
            <div class="alert alert-secondary" role="alert">
                {% translate "No one registered." %}
            </div>
            {% endif %}
            <table class="table table-hover">
                {% for registration in registrations %}
                <tr class="mb-3">
                    <td class="align-middle col-sm-9">{{ registration.registree.get_full_name }}</td>
                    <td><a class="btn btn-primary btn-sm" role="button" href="/planner/shift/{{ shift.id }}/unregister/{{ registration.registree.id }}">{% translate "Unregister" %}</a></td>
                </tr>
                        
                {% endfor %}

            </table>
            </ol>
        </div>
        <div class="col">
            <h4>{% translate "Available Employees" %}</h4>
            {% if not_registered_users %}{% else %}
            <div class="alert alert-secondary" role="alert">
                {% translate "All employees are registered." %}
            </div>
            {% endif %}
            <table class="table table-hover">
                {% for employee in not_registered_users %}
                <tr class="mb-3">
                    <td class="align-middle col-sm-9">{{ employee.get_full_name }}</td>
                    <td><a class="btn btn-primary btn-sm" role="button" href="/planner/shift/{{ shift.id }}/register/{{ employee.id }}">{% translate "Register" %}</a></td>
                {% endfor %}
                </table>
        </div>
    </div>
    <div class="row mb-3">
        <hr class="border border-secondary">
        <div class="col">
            <div class="btn-group" role="group" aria-label="Basic example">
                <a href="" class="btn btn-primary">{% translate "Back" %}</a>
                {% if user.is_staff %}
                {% if perms.shift_planner.change_shift %}
                    <a href="/admin/shift_planner/shift/{{ shift.id }}/change/" class="btn btn-secondary" target="_blank">{% translate "Update" %}</a>
                    {% endif %}
                    {% if perms.shift_planner.delete_shift %}
                        <a href="/admin/shift_planner/shift/{{ shift.id }}/delete/" class="btn btn-secondary" target="_blank">{% translate "Delete" %}</a>
                    {% endif %}
                {% endif %}
            </div>
            {% if perms.shift_planner.add_shift %}
                <a href="/admin/shift_planner/shift/add/" type="button" class="btn btn-secondary" target="_blank">{% translate "New" %}</a>
            {% endif %}
        </div>
    </div>
</div>



{% endblock %}

shift_planner/templates/shifts/list.html
{% extends "base.html" %}

{% block content %}

<h1>DEPRECATD SITE</h1>

<h2>My next Shifts</h2>

{% for shift in shifts %}
    <h3>
        {{ shift.date }}, {{ shift.starts_at }} - {{ shift.ends_at }}
    </h3>
    <p>Required: {{ shift.required_employees }}, registered: {{ shift.shiftregistration_set.count }}</p>
    {% if shift.is_registered == True %}
    <p>You are registered.</p>
    {% endif %}

    <a href="/planner/shift/{{ shift.id }}">Detail</a>
    {% if is_authenticated == True %}
        {% if shift.is_registered == False %}
            <a href="/planner/shift/{{ shift.id }}/register">Register</a>
        {% endif %}
        {% if shift.is_registered == True %}
            <a href="/planner/shift/{{ shift.id }}/unregister">Unregister</a>
        {% endif %}
    {% endif %}
{% endfor %}

{% endblock %}

shift_planner/templates/shifts/monthly.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}Shift Planner - Monthly View{% endblock %}
{% block content %}

    <div class="container m-4">
        <span class="col m-3" >
            <a class="col" href="/planner/monthly/{{ previous.year }}/{{ previous.month }}">{% translate "previous" %}</a>
        </span>
        <span class="col h2 m-3" >{{ first_day|date:"F Y" }}</span>
        <span class="col m-3" >
            <a class="col" href="/planner/monthly/{{ next.year }}/{{ next.month }}">{% translate "next" %}</a>
        </span>
    </div>
    <div class="container">

        {% with weeks=month.weeks %}
            {% with restrict_on_month=month.month %}
                {% include "shifts/weekly_calendar.html" %}
            {% endwith %}
        {% endwith %}
    </div>

{% endblock %}

shift_planner/templates/shifts/overview.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% translate "Shift Planner - My Overview" %}{% endblock %}
{% block content %}

    <!-- <div class="container">
        <h1>My Shift Plan</h1>
        <p class="lead">Use this document as a way to quickly start any new project.<br> All you get is this text and a mostly barebones HTML document.</p>
    </div> -->

    <div class="container-flex">
        <h2>{% translate "My next shifts" %}</h2>
        <p>{% translate "Next shifts I am registered for" %}</p>
        {% if my_next_shifts|length == 0 %}
            <div class="alert alert-secondary" role="alert">
                {% translate "You are not registered for any shifts." %}
            </div>
        {% else %}
            <div class="card-group">
                {% with cards_with_date=True %}
                    {% for shift in my_next_shifts %}
                        {% include "shifts/shift_card.html" %}
                    {% endfor %}
                {% endwith %}
            </div>
        {% endif %}
    </div>

    <div class="container-flex">
        <h2>{% translate "Shifts within the next two weeks" %}</h2>
        {% with weeks=next_weeks %}
            {% include "shifts/weekly_calendar.html" %}
        {% endwith %}
    </div>

{% endblock %}

shift_planner/templates/shifts/shift_card.html
{% load i18n %}
<!-- <div class="card mb-3 {% if shift.is_past == True %}text-secondary{% endif %}{% if shift.is_registered == True %}border-primary{% else %}{% endif %}"> -->
    <div class="card mb-3 {% if shift.is_past == True %}text-secondary{% endif %}{% if shift.is_registered == True %}border-primary{% else %}{% endif %}" style="max-width: 500px;">
    <div class="card-header">
        {% if cards_with_date %}
        <div class="text-center">{{ shift.shift_date|date:"l" }}</div>    
        <div class="text-center">{{ shift.shift_date }}</div>
        {% else %}
            <div class="d-md-none d-block text-center">{{ shift.shift_date|date:"l" }}</div>    
            <div class="d-md-none d-block text-center">{{ shift.shift_date }}</div>
        {% endif %}
        <span>{{ shift.starts_at|time:"H:i" }}-{{ shift.ends_at|time:"H:i" }}</span>
    </div>
    <div class="card-body">
        <p>
            <h5 class="card-title">{{ shift.title }}</h5>
        </p>
        {% if shift.is_registered == True %}
            <p class="alert alert-info">{% translate "I'm registered" %}</p>
        {% endif %}
        <p>
        {% if perms.shift_planner.does_planning %}
            {% if shift.required_employees_min > shift.registered_employees %}
                <div class="alert alert-danger" role="alert">
                    {% translate "Understaffed." %}
                </div>
            {% endif %}
        {% endif %}
        </p>
        <div>

            {% if shift.is_past == False %}
                {% if shift.is_registered == False %}
                    <a class="btn btn-primary mb-3" role="button" href="/planner/shift/{{ shift.id }}/register">{% translate "Register" %}</a>
                {% endif %}
                {% if shift.is_registered == True and shift.unregister_possible == True %}
                    <a class="btn btn-primary mb-3" role="button" href="/planner/shift/{{ shift.id }}/unregister">{% translate "Unregister" %}</a>
                {% endif %}
            {% endif %}
            {% if perms.shift_planner.does_planning %}
                <a class="btn btn-secondary mb-3" href="/planner/shift/{{ shift.id }}">{% translate "Detail" %}</a>
                <!-- <a class="card-link"href="/planner/shift/{{ shift.id }}">{% translate "Detail" %}</a> -->
            {% endif %}
        </div>
    </div>
</div>

shift_planner/templates/shifts/shift_carousel.html
<div id="next_three_shifts" class="carousel slide" data-bs-ride="carousel">
    <div class="row">
        <div class="carousel-inner">
            <!-- TODO Verschönerung möglich mit: https://getbootstrap.com/docs/5.3/components/carousel/#how-it-works -->
            {% with shifts=my_next_shifts %}
                {% with cards_with_date=True %}
                    <div class="carousel-item active">
                        {% with shift=shifts.0 %}
                            {% include "shifts/shift_card.html" %}
                        {% endwith %}
                    </div>
                    <div class="carousel-item">
                        {% with shift=shifts.1 %}
                            {% include "shifts/shift_card.html" %}
                        {% endwith %}
                    </div>
                    <div class="carousel-item">
                        {% with shift=shifts.2 %}
                            {% include "shifts/shift_card.html" %}
                        {% endwith %}
                    </div>
                {% endwith %}
            {% endwith %}
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#next_three_shifts" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#next_three_shifts" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
        </button>
    </div>
</div>

shift_planner/templates/shifts/weekly_calendar.html
{% load i18n %}

{% translate "Monday"    as Monday %}
{% translate "Tuesday"   as Tuesday %}
{% translate "Wednesday" as Wednesday %}
{% translate "Thursday"  as Thursday %}
{% translate "Friday"    as Friday %}
{% translate "Saturday"  as Saturday %}
{% translate "Sunday"    as Sunday %}

<!-- inspired by https://codepen.io/chrisdpratt/pen/OOybam -->
<div class="container-flex d-sm-none d-md-block">
    <header>
        <div class="row d-none d-sm-flex p-1 bg-dark text-white">
            <h5 class="col-sm p-1 text-center">{{ Monday }}</h5>
            <h5 class="col-sm p-1 text-center">{{ Tuesday }}</h5>
            <h5 class="col-sm p-1 text-center">{{ Wednesday }}</h5>
            <h5 class="col-sm p-1 text-center">{{ Thursday }}</h5>
            <h5 class="col-sm p-1 text-center">{{ Friday }}</h5>
            <h5 class="col-sm p-1 text-center">{{ Saturday }}</h5>
            <h5 class="col-sm p-1 text-center">{{ Sunday }}</h5>
        </div>
    </header>
    <!-- weekly calendar view --> 
    {% for week in weeks %}
        <div class="row border border-right-0 border-bottom-0">
            {% for day in week.days %}
                <div class="col-sm p-2 border border-left-0 border-top-0 d-sm-inline-block d-none {% if day.is_past == True %} bg-light text-muted {% endif %}">
                    {% if not restrict_on_month or restrict_on_month == day.date.month %}
                        <h5 class="row align-items-center">
                            <span class="date col-1">{{ day.date|date:"j" }}</span>
                            <small class="col d-sm-none text-center text-muted">{{ day.date|date:"l" }}</small>
                            <span class="col-1"></span>
                        </h5>
                        <p class="align-items-right text-truncate col">{{ day.holiday.name }}</p>
                        {% for shift in day.shifts %}
                            {% include "shifts/shift_card.html" %}
                        {% endfor %}
                    {% endif %}
                </div>
            {% endfor %}
        </div>
    {% endfor %}
</div>
<div class="container-flex d-block d-md-none">
    <!-- xs list view -->
    {% for week in weeks %}
            {% for day in week.days %}
                {% if not restrict_on_month or restrict_on_month == day.date.month %}
                    {% for shift in day.shifts %}
                        {% include "shifts/shift_card.html" %}
                    {% endfor %}
                {% endif %}
            {% endfor %}
    {% endfor %}
</div>